import { Card, CardContent } from '@/components/ui/card'

export function Terms() {
  return (
    <div className="max-w-2xl space-y-4">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Terms of Use</h1>
        <p className="text-sm text-muted-foreground mt-0.5">Last updated: May 2026</p>
      </div>

      <Card>
        <CardContent className="pt-5">
          <div className="space-y-4 text-sm leading-relaxed text-foreground">
            <p>
              By using TransitWehh ("the dashboard"), you agree to the following terms. If you do not
              agree, please do not use this service.
            </p>

            <div>
              <h3 className="font-semibold mb-1">Data accuracy disclaimer</h3>
              <p className="text-muted-foreground">
                Ridership figures are as reported by transport operators to the Malaysian Government
                and published on{' '}
                <a
                  href="https://data.gov.my"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline underline-offset-2 hover:opacity-80"
                >
                  data.gov.my
                </a>
                . TransitWehh makes no guarantees about the accuracy, completeness, or timeliness of
                the data displayed. Figures may be subject to revision by the original data providers.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-1">Source attribution</h3>
              <p className="text-muted-foreground">
                All ridership data is sourced from the Malaysian Government Open Data portal (
                <a
                  href="https://data.gov.my"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline underline-offset-2"
                >
                  data.gov.my
                </a>
                ). Data is used in accordance with the{' '}
                <a
                  href="https://www.data.gov.my/data/en_US/licence"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary underline underline-offset-2"
                >
                  Malaysian Open Data Licence
                </a>
                .
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-1">No warranty</h3>
              <p className="text-muted-foreground">
                This dashboard is provided "as is" without any warranty of any kind, express or implied.
                TransitWehh is not affiliated with, endorsed by, or officially connected to Prasarana,
                KTMB, Rapid KL, or any Malaysian government agency. Use of this dashboard for
                operational or safety-critical decisions is not recommended.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-1">Forecasts and analysis</h3>
              <p className="text-muted-foreground">
                Ridership forecasts are generated by statistical models (Facebook Prophet) and are
                provided for informational purposes only. They are not official projections and should
                not be relied upon for investment, policy, or operational decisions.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-1">My50 calculator</h3>
              <p className="text-muted-foreground">
                The My50 pass calculator provides illustrative estimates based on publicly available
                fare information. Actual savings may vary based on individual travel patterns, route
                availability, and any fare changes. Always verify current fares with the respective
                transport operators.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-1">Limitation of liability</h3>
              <p className="text-muted-foreground">
                To the maximum extent permitted by law, TransitWehh and its maintainers shall not be
                liable for any direct, indirect, incidental, or consequential damages arising from
                the use of or inability to use this dashboard.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
